version: '3.8'
services:
  postgresdb:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
    ports:
      - '$POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    depends_on:
      - postgresdb
    build: .
    restart: on-failure
    env_file: .env
    ports:
      - '$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT'
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://postgresdb:$POSTGRES_DOCKER_PORT/$POSTGRES_DATABASE?useSSL=false",
        "spring.datasource.username" : "$POSTGRES_USER",
        "spring.datasource.password" : "$POSTGRES_PASSWORD",
        "spring.datasource.driver-class-name" : "org.postgresql.Driver",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "$HIBERNATE_DDL_AUTO"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  postgres-data: